project:
  groupId: '@project.groupId@'
  artifactId: '@project.artifactId@'
  version: '@project.version@'
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  application:
    name: '@project.artifactId@'
  jpa:
    open-in-view: false
